default_locale: "en"
tabs:
  overview_project: "overview project"
  new_sprint: "new sprint"
  project_backlog: "project_backlog"
sprint:
  default_days: 10
  phases: "Phases"
product_add_more: [1, 3, 5, 10]
sprint_add_more_activities: [1, 5, 10]
